version: '3.1'

services:
#  app:
#    container_name: postgres_db
#    image: postgres
#    build: app-api
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres